# Generated by Django 4.0.5 on 2022-06-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='Book',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'books'},
        ),
    ]
