# Generated by Django 3.2.7 on 2022-06-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_image_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.BooleanField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=30),
        ),
    ]
