# Generated by Django 4.0.5 on 2022-07-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_issuedbook_pickup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrowed_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
