# Generated by Django 4.0.5 on 2022-07-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_borrower_options_alter_issuedbook_options'),
        ('books', '0010_fines_delete_borrowed_books_and_more'),
    ]

    operations = [
    ]
