# Generated by Django 4.0.5 on 2022-07-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_borrower_book_name_alter_issuedbook_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='book_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='first_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='last_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='reg_no',
            field=models.CharField(max_length=200),
        ),
    ]
