# Generated by Django 4.0.5 on 2022-07-06 20:04

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_borrower_book_name_alter_borrower_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('issued_date', models.DateField(auto_now=True)),
                ('return_date', models.DateField(default=books.models.get_return_date)),
                ('pickup_time', models.DateTimeField(default=books.models.book_time_limit)),
                ('borrower', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'requestedbooks',
            },
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.DeleteModel(
            name='Fines',
        ),
    ]
