# Generated by Django 4.0.5 on 2022-07-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_requestedbook_remove_issuedbook_issued_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issued_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=200)),
                ('reg_no', models.IntegerField()),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'verbose_name_plural': 'issuedbooks',
            },
        ),
        migrations.DeleteModel(
            name='IssuedBook',
        ),
    ]
