# Generated by Django 4.0.5 on 2022-07-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_issued_book_delete_issuedbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issued_Book',
            new_name='IssuedBook',
        ),
    ]
