# Generated by Django 4.0.5 on 2022-07-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_rename_issued_book_issuedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.borrower'),
        ),
    ]
