# Generated by Django 4.0.5 on 2022-07-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_issuedbook_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='reg_no',
            field=models.BigIntegerField(),
        ),
    ]
