# Generated by Django 4.0.5 on 2022-07-08 12:14

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_issuedbook_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedbook',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='requestedbook',
            name='return_date',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='issued_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='return_date',
            field=models.DateField(default=books.models.get_return_date),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
