# Generated by Django 4.0.5 on 2022-07-09 15:04

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0019_remove_requestedbook_issued_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='username',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedbook',
            name='return_date',
            field=models.DateField(default=books.models.get_return_date),
        ),
        migrations.CreateModel(
            name='Returned_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_return', models.DateTimeField(auto_now=True)),
                ('reg_no', models.BigIntegerField()),
                ('return_date', models.DateField(auto_now=True)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.issuedbook')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.borrower')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
